/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuardarKardex.java
 *
 * Created on 05-ago-2013, 12:01:31
 */

package kardexarchivo;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import java.sql.SQLException;
import java.util.Vector;
import java.sql.ResultSet;
/**
 *
 * @author edwin.cevallost
 */
public class GuardarKardex extends javax.swing.JDialog {
    private String _idjuicio;
    public Usuario user;
    /** Creates new form GuardarKardex */
    public GuardarKardex(java.awt.Frame parent, boolean modal, String idjuicio, Usuario u) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        user=u;
        //this.setMaximumSize(new Dimension(1024,800));
        this._idjuicio=idjuicio;
        DefaultComboBoxModel cmbTipos = new DefaultComboBoxModel(CargarTipo());
        this.cmbTipo.setModel(cmbTipos);
        DefaultComboBoxModel cmbUbicaciones = new DefaultComboBoxModel(CargarUbicacion());
        this.cmbUbicacion.setModel(cmbUbicaciones);
        DefaultComboBoxModel cmbUsuariosEntrega = new DefaultComboBoxModel();
        this.cmbEntrega.setModel(cmbUsuariosEntrega);
        DefaultComboBoxModel cmbUsuariosRecibe = new DefaultComboBoxModel();
        this.cmbRecibe.setModel(cmbUsuariosRecibe);
        this.txtRecibe.setText(user.usu_id);
        this.txtEntrega.setText(null);
        this.txtRecibe.setEnabled(false);
        this.txtEntrega.setEnabled(true);
        this.cmbRecibe.setVisible(false);
        this.cmbEntrega.setVisible(false);
        
        
    }
   public static Vector<Tipo> CargarTipo(){
        Vector<Tipo> tipos = new Vector<Tipo>();
        Tipo tp= null;
        ResultSet rs = null;
        BaseDatos bdd= new BaseDatos("INVENTARIO");
        bdd.Conectar();
        bdd.CrearStoreProcedure("exec proc_select_tipos");
        rs=bdd.EjecutarComando();
        try{
            while(rs.next()){
                tp= new Tipo(rs.getInt("tip_id"),rs.getString("tip_sigla"),rs.getString("tip_detalle"));
                tipos.add(tp);
            }
            rs.close();
        }catch(SQLException ex){
          System.out.println(ex);
        }
        return tipos;

    }

    public static Vector<Ubicacion> CargarUbicacion(){
        Vector<Ubicacion> ubicaciones = new Vector<Ubicacion>();
        Ubicacion ub= null;
        ResultSet rs = null;
        BaseDatos bdd= new BaseDatos("INVENTARIO");
        bdd.Conectar();
        bdd.CrearStoreProcedure("exec proc_select_ubicaciones");
        rs=bdd.EjecutarComando();
        try{
            while(rs.next()){
                ub= new Ubicacion(rs.getInt("ubi_id"),rs.getString("ubi_descripcion"));
                ubicaciones.add(ub);
            }
            rs.close();
        }catch(SQLException ex){
          System.out.println(ex);
        }
        return ubicaciones;

    }
    
    
  public static Vector<Usuario> CargarFuncionarios(String judicatura){
        Vector<Usuario> usuarios = new Vector<Usuario>();
        Usuario usu= null;
        ResultSet rs = null;
        BaseDatos bdd= new BaseDatos("satje");
        bdd.Conectar();
        bdd.CrearStoreProcedure("select Usuarios.Login as Login, Nombres as nombres, ApellidoPaterno+' '+ApellidoMaterno as apellidos , NombreCargo  from usuarios "+
"INNER JOIN UsuarioJudicatura "+
"ON UsuarioJudicatura.Login=Usuarios.Login "+
"inner join Judicaturas "+
"on judicaturas.IdJudicatura=UsuarioJudicatura.IdJudicatura "+
"inner join Cargos "+
"on cargos.IdCargo=UsuarioJudicatura.IdCargo "+
"where IdProvincia='ECU10' AND UsuarioJudicatura.IdJudicatura LIKE '"+judicatura+"' "+
"and Usuarios.Estado<>'X' and Cedula<>'' and Nombres <>'' "+
"order by usuariojudicatura.idcargo");
        rs=bdd.EjecutarComando();
        try{
            while(rs.next()){
                usu= new Usuario(rs.getString("login"),rs.getString("nombres"),rs.getString("apellidos"),rs.getString("NombreCargo"));
                usuarios.add(usu);
            }
            rs.close();
        }catch(SQLException ex){
          System.out.println(ex);
        }
        return usuarios;

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRecibe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmbUbicacion = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtProposito = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        cmbRecibe = new javax.swing.JComboBox();
        cmbEntrega = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kardexarchivo.KardexArchivoApp.class).getContext().getResourceMap(GuardarKardex.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        txtEntrega.setName("txtEntrega"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        txtRecibe.setName("txtRecibe"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipo.setName("cmbTipo"); // NOI18N
        cmbTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTipoMouseClicked(evt);
            }
        });
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        cmbUbicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUbicacion.setName("cmbUbicacion"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        txtProposito.setName("txtProposito"); // NOI18N

        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jCancelar.setText(resourceMap.getString("jCancelar.text")); // NOI18N
        jCancelar.setName("jCancelar"); // NOI18N
        jCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCancelarMouseClicked(evt);
            }
        });

        cmbRecibe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRecibe.setName("cmbRecibe"); // NOI18N

        cmbEntrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEntrega.setName("cmbEntrega"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProposito, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(93, 93, 93)
                        .addComponent(jCancelar)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(cmbRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtRecibe)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProposito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jCancelar))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        Tipo tp;
        tp=(Tipo)this.cmbTipo.getSelectedItem();
        Ubicacion ubi;
        ubi=(Ubicacion)this.cmbUbicacion.getSelectedItem();
        Registro registro = new Registro(_idjuicio,this.txtEntrega.getText(),this.txtRecibe.getText(),tp.getTip_id(),ubi.getUbi_id(),this.txtProposito.getText(),user.usu_id);
        registro.GuardarRegistro();
        if(txtRecibe.isEnabled()){
            Etiqueta etiquetaverde = new Etiqueta(4,_idjuicio);
            etiquetaverde.quitaretiqueta();
            Etiqueta etiquetaroja = new Etiqueta(3,_idjuicio);         
            etiquetaroja.poneretiqueta();
        }else{
            Etiqueta etiquetaverde = new Etiqueta(4,_idjuicio);
            etiquetaverde.poneretiqueta();
            Etiqueta etiquetaroja = new Etiqueta(3,_idjuicio);         
            etiquetaroja.quitaretiqueta();
        }
        dispose();
      
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void jCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCancelarMouseClicked

    private void cmbTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTipoMouseClicked

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:

         if (evt.getStateChange() == evt.SELECTED) {
              Tipo tp;
            tp=(Tipo)this.cmbTipo.getSelectedItem();
           // System.out.println(tp.getTip_siglas());
                 if(tp.getTip_siglas().trim().equals("IN")){
                    this.cmbRecibe.setSelectedItem(user.usu_id); 
                    this.txtRecibe.setText(user.usu_id);
                    this.txtEntrega.setText(null);
                    this.txtRecibe.setEnabled(false);
                    this.txtEntrega.setEnabled(true);
                }else{
                    this.cmbEntrega.setSelectedItem(user.usu_id); 
                    this.txtEntrega.setText(user.usu_id);
                    this.txtRecibe.setText(null);
                    this.txtRecibe.setEnabled(true);
                    this.txtEntrega.setEnabled(false);
                }
         }
    }//GEN-LAST:event_cmbTipoItemStateChanged

private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_btnGuardarMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuardarKardex dialog = new GuardarKardex(new javax.swing.JFrame(), true,"", new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbEntrega;
    private javax.swing.JComboBox cmbRecibe;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JComboBox cmbUbicacion;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtProposito;
    private javax.swing.JTextField txtRecibe;
    // End of variables declaration//GEN-END:variables

}
