/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reporteIngresados.java
 *
 * Created on 18-ago-2013, 18:37:18
 */

package kardexarchivo;

import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MEGASYSTEM
 */
public class reporteEtiquetas extends javax.swing.JDialog {

    /** Creates new form reporteIngresados */
    public reporteEtiquetas(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(parent);
    DefaultComboBoxModel mdlEtiquetas = new DefaultComboBoxModel(CargarEtiquetas());
    this.cmbEtiquetas.setModel(mdlEtiquetas);
       
    }
public static Vector<Etiqueta> CargarEtiquetas(){
        Vector<Etiqueta> etiquetas = new Vector<Etiqueta>();
        Etiqueta et= null;
        ResultSet rs = null;
        BaseDatos bdd= new BaseDatos("INVENTARIO");
        bdd.Conectar();
        bdd.CrearStoreProcedure("exec proc_select_etiquetas_reporte");
        rs=bdd.EjecutarComando();
        try{
                et= new Etiqueta();
                et.setEt_id(0);
                et.setEt_nombre("");
                etiquetas.add(et);
            while(rs.next()){
                et= new Etiqueta();
                et.setEt_id(rs.getInt("et_id"));
                et.setEt_nombre(rs.getString("et_nombre"));
                etiquetas.add(et);
            }
            rs.close();
        }catch(SQLException ex){
          System.out.println(ex);
        }
        return etiquetas;

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbEtiquetas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kardexarchivo.KardexArchivoApp.class).getContext().getResourceMap(reporteEtiquetas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Form"); // NOI18N
        setResizable(false);

        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setName("btnImprimir"); // NOI18N
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirMouseClicked(evt);
            }
        });

        btnSalir.setText(resourceMap.getString("btnSalir.text")); // NOI18N
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        cmbEtiquetas.setName("cmbEtiquetas"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnSalir))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseClicked
         try{
                BaseDatos reporte = new BaseDatos("INVENTARIO");
                reporte.Conectar();
                Etiqueta et=new Etiqueta();
                et= (Etiqueta) cmbEtiquetas.getSelectedItem();
                Map map = new HashMap();
                int etiqueta;
                etiqueta=et.et_id;
                map.put("etiqueta", etiqueta);
                String path=System.getProperty("user.dir");
                JasperReport masterReport= JasperCompileManager.compileReport(path+"\\rptEtiquetas.jrxml");
                JasperPrint print = JasperFillManager.fillReport(masterReport, map, reporte.conn);
                JasperViewer jReportsViewer = new JasperViewer(print,false);
                        
                jReportsViewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
                jReportsViewer.setVisible(true);
                //jReportsViewer.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE );
                  //  JasperPrint jasperPrinter = JasperFillManager.fillReport(jasperReport, m, new DataConnection().getConnection());
                 // this.add(jReportsViewer);
         }catch(Exception ex){
            System.out.println(ex);
         }
    }//GEN-LAST:event_btnImprimirMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                reporteEtiquetas dialog = new reporteEtiquetas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbEtiquetas;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
